version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"   # Can be "weekly", "monthly", or "daily"
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
