version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  # Can be "weekly", "monthly", or "daily"
    commit-message:
      prefix: "UPDATE"   # Custom commit message prefix
    open-pull-requests-limit: 5